version: 0.2 
phases: 
  install: 
    runtime-versions: 
      python: 3.8 
  pre_build: 
    commands: 
      - echo logging in to AWS ECR...   
      - $(aws ecr get-login --no-include-email --region us-west-2)   
  build:   
    commands:   
      - echo build Docker image on `date`   
      - docker build -t test:latest .   
      - docker tag test:latest 773358635836.dkr.ecr.us-west-2.amazonaws.com/versionapi:volvo-v1   
  post_build:   
    commands:   
      - echo build Docker image complete `date`   
      - echo push latest Docker images to ECR...   
      - docker push 773358635836.dkr.ecr.us-west-2.amazonaws.com/versionapi:volvo-v1
      - printf '{"ImageURI":"image_URI"}' > imageDetail.json
      - pwd 
      - ls 
artifacts: 
  files: 
    - imageDetail.json 
